version: '3.8'
services:
  api:
    image: ${DOCKER_REGISTRY}/${DOCKER_CREDENTIALS_USR}/${DOCKER_IMAGE}:${BUILD_NUMBER}
    container_name: talentexis-api
    ports:
      - "8081:8080"  # Changed to 8081 to avoid conflict with Jenkins
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge